config/routes.rb
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do

  get '/about', to: 'about#index'
  get '/countries(/:id)', to: 'countries#show', as: 'countries_show'
  get '/dashboards', to: redirect('/dashboards/global')
  get '/dashboards(/:mode)(/:id)', to: 'dashboards#show', as: 'dashboards_show'

  root 'welcome#index'
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  def show
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/index.html.erb
<div class="l-content-large -about -image">
  <%= render 'shared/header', class_name: '-transparent' %>
  <%= render 'shared/share_menu', class_name: '-transparent' %>
  <div class="row">
    <div class="columns small-12 medium-8">
      <div class="c-cta -header">
        <h1 class="text -cta-title-header -light">About</h1>
        <p class="text -cta-text -light">The results presented here are based on a joint research effort between the World Bank Group, Results for Development Institute, and 1,000 Days, with financial support from the Bill & Melinda Gates Foundation and the Children’s Investment Fund Foundation.</p>
      </div>
    </div>
  </div>
  <div class="smooth-scroll">
    <a href="#find-out-more" class="js-btn-smooth-scroll">
      <svg class="icon"><use xlink:href="#icon-scroll"></use></svg>
    </a>
  </div>
</div>

<div id="find-out-more">
  <div class="row">
    <div class="columns small-12 medium-8">
      <div class="l-content -first">
        <p class="text">Please refer to the publication <a href=" https://openknowledge.worldbank.org/handle/10986/26069" target="_blank" rel="noopener">“An investment framework for nutrition: reaching the global targets for stunting, anemia, breastfeeding and wasting”</a> for a detailed description of the methodology. </p>
      </div>
    </div>
  </div>
</div>

<div class="l-content">
  <div class="row">
    <div class="columns small-12">
      <hr class="c-separator"/>
      <a href="http://www.worldbank.org/" target="_blank" rel="noopener">
        <svg class="icon"><use xlink:href="#icon-world-bank"></use></svg>
      </a>
    </div>
    <div class="columns small-12 medium-6">
      <p class="text">
        Under its twin goals of reducing poverty and boosting shared prosperity, the World Bank has played a major role in supporting the scale-up of actions to prevent stunting. Over the last decade, the World Bank led the development of several landmark publications on nutrition, including Repositioning Nutrition as Central to Development and Scaling Up Nutrition: What will it cost? More recently, this effort has been spearheaded by President Jim Yong Kim, who said, “In too many low- and middle-income countries, children are disadvantaged before they even set foot in school because they did not have adequate early nutrition and stimulation, or were exposed to toxic environments.
      </p>
    </div>
    <div class="columns small-12 medium-6">
      <p class="text">
        Childhood stunting rates of 45 percent – and as high as 70 percent in some countries – are a stain on our collective conscience”.  Reducing stunting is central to the “Investing in the Early Years” mandate now center stage on the Bank’s agenda, which involves strengthening actions across several key sectors.  To this end, the World Bank recently led the efforts to create an investment framework for nutrition in order to reach the World Health Assembly global targets for stunting, anemia, breastfeeding, and wasting.
      </p>
    </div>
  </div>
</div>

<div class="l-content">
  <div class="row">
    <div class="columns small-12">
      <hr class="c-separator"/>
      <a href="http://www.r4d.org/" target="_blank" rel="noopener">
        <svg class="icon -r4d"><use xlink:href="#icon-logo"></use></svg>
      </a>
    </div>
    <div class="columns small-12 medium-6">
      <p class="text">
        Results for Development (R4D) is a global nonprofit organization working with partners in more than 55 countries to find new ways to help people escape poverty and reach their full potential. We apply fresh thinking and rigor to emerging and stubborn development challenges — particularly within the fields of health, education and governance — and we pioneer and advance creative, high-impact solutions.
      </p>
    </div>
    <div class="columns small-12 medium-6">
      <p class="text">
        We do this by conducting analysis that helps to inform and influence decision-makers; building platforms and networks that connect people and ideas; providing direct support to local change agents; and combining these approaches to deliver meaningful and lasting results. R4D specializes in health and nutrition financing analytics, including resource tracking for nutrition, both at the country and global levels. In the partnership for the Investment Framework for Nutrition, R4D led the financing analysis.
      </p>
      <br>
      <p>
        <a href="http://www.r4d.org/focus-areas/nutrition" target="_blank" rel="noopener"> For more on R4D’s nutrition work, click here</a>.
      </p>
    </div>
  </div>
</div>

<div class="l-content">
  <div class="row">
    <div class="columns small-12">
      <hr class="c-separator"/>
      <a href="http://thousanddays.org/" target="_blank" rel="noopener">
        <svg class="icon -days"><use xlink:href="#icon-days"></use></svg>
      </a>
    </div>
    <div class="columns small-12 medium-6">
      <p class="text">
        1,000 Days is the leading non-profit organization promoting action and investment in nutrition to build a strong foundation for children, their families and their nations to thrive.
      </p>
    </div>
    <div class="columns small-12 medium-6">
      <p class="text">
        By coordinating with partners in the U.S. and around the world, 1,000 Days has played an important role in communicating the need for investment to policymakers and disseminating the breakthrough analysis by the World Bank and Results for Development (R4D) globally.
      </p>
    </div>
  </div>
</div>

<div class="l-content">
  <div class="row">
    <div class="columns small-12">
      <hr class="c-separator"/>
    </div>
    <div class="columns small-12 medium-3">
      <a href="http://www.gatesfoundation.org/" target="_blank" rel="noopener">
        <svg class="icon"><use xlink:href="#icon-gates-foundation"></use></svg>
      </a>
    </div>
    <div class="columns small-12 medium-3">
      <a href="https://ciff.org/" target="_blank" rel="noopener">
        <svg class="icon"><use xlink:href="#icon-ciff"></use></svg>
      </a>
    </div>
    <div class="columns small-12">
      <p class="text">
        This work was funded by the Bill and Melinda Gates Foundation and the Children’s Investment Fund Foundation.
      </p>
    </div>
    <div class="columns small-12">
      <div class="last"></div>
    </div>
  </div>
</div>

app/views/countries/show.html.erb
<%= render 'shared/header', class_name: '-normal' %>
<%= render 'shared/share_menu', class_name: '-normal' %>

<div id="map-section" class="l-map l-ajax-loader -countries">
  <div class="spinner"></div>
  <div class="row">
    <div class="columns small-12">
      <div id="countryMapView">
        <div class="columns small-12 medium-6 medium-offset-3">
          <div id="countrySelectorView">
            <select name="group" id="groupSelector" class="js--country-selector"></select>
          </div>
        </div>
        <div id="map-container" class="c-map-home"></div>
        <div class="row">
          <div class="columns small-12 medium-5 medium-offset-7">
            <div class="c-countries-map-legend no-print">
              <ul>
                <li>
                  <span class="color-code -donor-gov"></span>
                  <span class="text -legend">Data available on domestic and donor investments in nutrition</span>
                </li>
                <li>
                  <span class="color-code -only-donor"></span>
                  <span class="text -legend">Data on only donor investments in nutrition available</span>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="smooth-scroll">
      <a href="#data-section" class="js-btn-smooth-scroll">
        <svg class="icon"><use xlink:href="#icon-scroll"></use></svg>
      </a>
    </div>
  </div>
</div>

<div class="row">
  <div class="columns small-12">
    <div id="data-section" class="l-content -top placeholder"></div>
  </div>
  <div class="columns small-12 large-6">
    <div id="currentCountryGovernment" class="l-chart l-ajax-loader">
      <div id="governmentFundingText"></div>
      <div class="spinner"></div>
      <div class="c-chart"></div>
      <div id="governmentFundingFootnote"></div>
    </div>
  </div>
  <div class="columns small-12 large-6">
    <div id="currentCountryDonor" class="l-chart l-ajax-loader">
      <div id="currentDonorFundingText"></div>
      <div class="spinner"></div>
      <div class="c-chart -burden"></div>
    </div>
  </div>
  <div class="columns small-12">
    <p class="text -footnote">Source: Creditor Reporting System for the OECD Database; Sources of government contributions are listed in Chapter 8 of <a href="https://openknowledge.worldbank.org/handle/10986/26069" target="_blank">“An Investment Framework for Nutrition: reaching the global targets for stunting, anemia, breastfeeding and wasting”</a></p>
  </div>
  <div class="columns small-12">
    <div class="l-content -last"></div>
  </div>
</div>

app/views/dashboards/show.html.erb
<%= render 'shared/header', class_name: '-normal' %>
<%= render 'shared/share_menu', class_name: '-normal' %>

<div class="l-selectors">
  <div class="row">

    <div class="column small-12 medium-8 medium-offset-2 large-6 large-offset-3">
      <div id="modeSelectorView" class="c-tabs">
        <div class="tab">
          <input type="radio" name="mode" value="global" class="js--mode-selector" id="global">
          <label for="global" class="text -tabs">Global</label>
        </div>
        <div class="tab">
          <input type="radio" name="mode" value="region" class="js--mode-selector" id="region">
          <label for="region" class="text -tabs">Regions</label>
        </div>
        <div class="tab">
          <input type="radio" name="mode" value="income_group" class="js--mode-selector" id="income_group">
          <label for="income_group" class="text -tabs">Income groups</label>
        </div>
      </div>
      <div id="groupSelectorView">
        <select name="group" id="groupSelector" class="js--group-selector"></select>
      </div>
    </div>
  </div>
</div>

<section id="mapTitleView" class="title-section l-ajax-loader l-map">
  <div class="spinner"></div>
  <div class="row">
    <div class="columns small-12 medium-6">
      <div id="map" class="c-map-regions"></div>
    </div>
    <div class="columns small-12 medium-6">
      <p class="text print-text-half">If the world meets the global nutrition targets, 3.7 million child lives could be saved, at least 65 million fewer children would be stunted, 265 million fewer women would suffer from anemia, and 91 million children would be treated for severe wasting. Achieving these results would require an average annual investment of $7 billion over the next 10 years to scale-up a package of high-impact nutrition interventions. On top of this, improvements in the enabling environment are necessary. Achieving the targets is within reach if all partners work together to immediately scale-up investments in nutrition.</p>
    </div>
  </div>
</section>

<section id="commonNutritionSection" class="l-ajax-loader">
  <div class="spinner"></div>
  <div class="row">
    <div class="columns small-12">
      <hr class="c-separator"/>
      <h2 class="text -title">How common are nutritional conditions?</h2>
      <h3 class="text -subtitle">Prevalence of nutritional conditions</h3>
    </div>
    <div class="columns small-12 large-8">
      <div id="currentBurdenView" class="l-chart">
        <div class="c-chart -burden"></div>
      </div>
    </div>
    <div class="columns small-12 large-4">
      <p class="text offset-print">Stunting, wasting, anemia, and non-exclusive breastfeeding are common indicators of malnutrition. In this chart, stunting and wasting are shown as a percentage of children under 5, anemia as a percentage of women of reproductive age, and non-exclusive breastfeeding as a percentage of infants in their first 6 months.</p>
    </div>
  </div>
</section>

<section id="costGoalsSection" class="l-ajax-loader">
  <div class="spinner"></div>
  <div class="row">
    <div class="columns small-12">
      <hr class="c-separator"/>
      <h2 id="chartTitleView" class="text -title">How much will it cost to achieve the targets global leaders set?</h2>
    </div>
    <div class="column small-12 medium-6">
      <p class="text" id="costTitleView">Achieving the WHA targets will cost $3 billion over 10 years, on top of current investments. However, if current investments continue under Business as Usual, the targets will not be achieved. Achieving the targets is within reach if all partners work together to immediately scale-up investments in nutrition under Global Solidarity.</p>
    </div>
    <div class="column small-12 medium-6">
      <p class="text">Note that because some interventions contribute to more than one target, the cost of meeting all four targets is less than the sum of meeting all four targets individually.</p>
    </div>
    <div class="columns small-12">
      <h3 class="text -subtitle">Cost of meeting targets on top of current spending, 2016-2025 (USD 2015)</h3>
    </div>
    <div class="columns small-12 medium-12">
      <div id="costMeetingPackagesView" class="l-chart">
        <div class="c-chart"></div>
      </div>
    </div>
  </div>
</section>

<section id="packageComparisonSection" class="l-ajax-loader">
  <div class="spinner"></div>
  <div class="row">
    <div class="columns small-12">
      <hr class="c-separator"/>
      <!-- <div class="print-break"></div> -->
      <h2 class="text -title">Under constrained resources, how much would it cost to deliver priority interventions?</h2>
      <h3 class="text -subtitle">Cost of packages comparison</h3>
      <div id="costPackagesView" class="l-chart">
        <div class="c-chart"></div>
      </div>
      <div id="costPackagesViewPrint" class="l-chart">
        <div class="c-chart"></div>
      </div>
    </div>
    <div class="column small-12 medium-6">
      <p class="text">In a resource-constrained setting, priority should be given to a narrower package including the most cost-effective interventions that have high technical efficiency and can be scaled-up immediately.</p>
    </div>
    <div class="column small-12 medium-6">
      <p class="text">Scaling up this priority package would cost less than scaling up a package of all interventions needed reach the WHA targets. However, the targets would not be achieved under this low-cost scale-up scenario.</p>
    </div>
    <div class="columns small-12  no-print">
      <button class="text -button js-btn-action" data-action="Info:toggle">See what the packages include</button>
    </div>
  </div>
</section>

<section id="fullPrioritySection" class="l-ajax-loader">
  <div class="spinner"></div>
  <div class="row">
    <div class="columns small-12">
      <hr class="c-separator"/>
      <h2 class="text -title">How can the funding be mobilized?</h2>
    </div>
    <div class="columns small-12 medium-4 medium-offset-8 no-print">
      <span class="text">Choose intervention package</span>
    </div>
    <div class="columns small-12 medium-8">
      <h3 class="text -subtitle">Financing the targets through Business as Usual vs. Global Solidarity<span class="switch-text print"> (full)</span></h3>
    </div>
    <div class="columns small-12 medium-4 no-print">
        <div id="graphModeSwitcher" class="c-mode-switcher">
          <div class="row">
            <div class="columns small-6">
              <button class="btn -is-active -line js--graph-switcher" mode="Full">full</button>
            </div>
            <div class="columns small-6">
              <button class="btn -line js--graph-switcher" mode="Priority">priority</button>
            </div>
          </div>
      </div>
    </div>
    <div class="columns small-12 medium-6">
      <div id="businessAsUsualView" class="l-chart">
        <div class="c-chart"></div>
      </div>
      <p class="text">Under a <b>Business as Usual</b> scenario—where current funding for nutrition grows based on economic growth but nutrition prioritization remains unchanged—there will be a substantial funding gap and the targets will not be achieved. Mobilizing the resources needed to accelerate progress against malnutrition will require that donors, countries, innovative financing mechanisms, businesses, and consumers act in solidarity. </p>
    </div>
    <div class="columns small-12 medium-6">
      <div id="globalSolidarityView" class="l-chart -secondary">
        <div class="c-chart"></div>
      </div>
      <p class="text">In the <b>Global Solidarity</b> scenario—where nutrition commitments are made and all additional resources are mobilized through coordinated global effort—donor spending scales up rapidly during the next five years, while domestic spending steadily grows. Then, from 2020 to 2025, domestic financing accelerates, and donors begin to scale back in support of country ownership over nutrition programming.</p>
    </div>
    <div class="columns small-12">
      <p class="text -footnote">*Current spending is maintained across the ten year period. Annual figures represent total contributions by source, including projected levels of current spending as well as additional financing needs to scale-up the interventions. Figures do not include costs to scale-up IPTp (total cost = $0.5 B), as it is currently being funded by sources outside of nutrition, including the President’s Malaria Initiative, the Global Fund to Fight AIDS, TB and Malaria, and to some extent country governments.</p>
    </div>
  </div>
</section>

<section id="additionalInfoView" class="title-section l-ajax-loader">
  <div class="spinner"></div>
  <div class="row">
    <div class="columns small-12">
      <div class="l-content -last">
        <hr class="c-separator"/>
        <p class="text two-column">
          If [region] and others worldwide do their part, the results could be tremendous: 3.7 million child lives saved, at least 65 million fewer stunted children, 265 million fewer women suffering from anemia than in 2015, and 91 million children treated for severe wasting. In a resource-constrained environment, the smaller package of priority interventions could save about 2.2 million lives, and-together with anticipated progress in food availability and diversity, women's health and education, and investments in water and sanitation-could result in 50 million fewer children stunted in 2025 compared to 2015. It would also result in 91 million children treated for severe wasting.
        </p>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Invest In Nutrition</title>
    <meta name="description" content="Visualize the resources needed and current funding available to reduce malnutrition worldwide.">

    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:700|Raleway:300,400,700" rel="stylesheet">

    <!-- style sheets and js -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- for Facebook -->
    <meta property="og:title" content="The urgent need for global action on nutrition | Invest In Nutrition" />
    <meta property="og:url" content="" />
    <meta property="og:image" content=<%= image_url("investing_nutritions.png")%> />
    <meta property="og:description" content="Visualize the resources needed and current funding available to reduce malnutrition worldwide." />

    <!-- for Twitter -->
    <meta name="twitter:title" content="The urgent need for global action on nutrition | Invest In Nutrition" />
    <meta property="twitter:image" content=<%= image_url("investing_nutritions.png")%> />
    <meta name="twitter:description" content="Visualize the resources needed and current funding available to reduce malnutrition worldwide." />
    <meta property="twitter:url" content="" />

    <!-- favicons -->
    <link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path('favicons/apple-touch-icon.png') %>">
    <link rel="icon" type="image/png" href="<%= asset_path('favicons/favicon-32x32.png') %>" sizes="32x32">
    <link rel="icon" type="image/png" href="<%= asset_path('favicons/favicon-16x16.png') %>" sizes="16x16">
    <link rel="manifest" href="<%= asset_path('favicons/manifest.json') %>">
    <link rel="mask-icon" href="<%= asset_path('favicons/safari-pinned-tab.svg') %>" color="#5bbad5">
    <meta name="theme-color" content="#ffffff">

    <!-- SVG icons -->
    <%= render 'shared/icons' %>

    <!-- datamaps -->
    <script src="https://d3js.org/d3.geo.projection.v0.min.js"></script>
    <script src="https://d3js.org/topojson.v1.min.js"></script>
    <script src="https://datamaps.github.io/scripts/datamaps.world.min.js?v=1"></script>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-8479985-19', 'auto');
      ga('send', 'pageview');
    </script>

  </head>

  <body>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class="l-footer no-print">
  <div class="row">
    <div class="column small-12">
      <ul class="c-navigation">
        <li class="text -menu <%= "-active" if controller_name == 'welcome' %>"><%= link_to 'The challenge', '/' %></li>
        <li class="text -menu <%= "-active" if controller_name == 'dashboards' %>"><%= link_to 'Financing Needs', '/dashboards/global' %></li>
        <li class="text -menu <%= "-active" if controller_name == 'countries' %>"><%= link_to 'Current Funding', countries_show_path %></li>
        <li class="text -menu <%= "-active" if controller_name == 'about' %>"><%= link_to 'About', about_path %></li>
      </ul>
      <ul class="c-partners">
        <li>
          <a href="http://www.worldbank.org/" target="_blank" rel="noopener">
            <svg class="icon"><use xlink:href="#icon-world-bank"></use></svg>
          </a>
        </li>
        <li>
          <a href="http://www.r4d.org/" target="_blank" rel="noopener">
            <svg class="icon"><use xlink:href="#icon-logo"></use></svg>
          </a>
        </li>
        <li>
          <a href="http://www.gatesfoundation.org/" target="_blank" rel="noopener">
            <svg class="icon"><use xlink:href="#icon-gates-foundation"></use></svg>
          </a>
        </li>
        <li>
          <a href="https://ciff.org/" target="_blank" rel="noopener">
            <svg class="icon"><use xlink:href="#icon-ciff"></use></svg>
          </a>
        </li>
        <li>
          <a href="http://thousanddays.org/" target="_blank" rel="noopener">
            <svg class="icon"><use xlink:href="#icon-days"></use></svg>
          </a>
        </li>
      </ul>
      <div class="designed-by">
        <p class="text designed -footnote">Designed by: </p>
        <a href="http://www.vizzuality.com/" target="_blank" rel="noopener" class="vizz-logo"></a>
      </div>
      <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener"><p class="text -footnote -center">Creative Commons 4.0 license</p></a>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<div class="row no-print">
  <div class="columns small-12">
    <div class="l-header <%= class_name %>">
      <div class="logo">
        <a class="text -logo" href="/">
          Investing in Nutrition
        </a>
      </div>
      <div class="desktop">
        <ul class="c-navigation <%= class_name %>">
          <li class="text -menu <%= "-active" if controller_name == 'welcome' %>"><%= link_to 'The challenge', '/' %></li>
          <li class="text -menu <%= "-active" if controller_name == 'dashboards' %>"><%= link_to 'Financing Needs', '/dashboards/global' %></li>
          <li class="text -menu <%= "-active" if controller_name == 'countries' %>"><%= link_to 'Current Funding', countries_show_path %></li>
          <li class="text -menu <%= "-active" if controller_name == 'about' %>"><%= link_to 'About', about_path %></li>
        </ul>
      </div>
      <div class="js-btn-mobile-menu mobile">
        <svg class="icon -open"><use xlink:href="#icon-menu"></use></svg>
        <svg class="icon -close"><use xlink:href="#icon-close"></use></svg>
      </div>
      <div class="c-mobile-menu <%= class_name %>">
        <ul class="c-navigation <%= class_name %>">
          <li class="text -menu <%= "-active" if controller_name == 'dashboards' %>"><%= link_to 'Financing Needs', '/dashboards/global' %></li>
          <li class="text -menu <%= "-active" if controller_name == 'dashboards' %>"><%= link_to 'Financing Needs', '/dashboards/global' %></li>
          <li class="text -menu <%= "-active" if controller_name == 'countries' %>"><%= link_to 'Current Funding', countries_show_path %></li>
          <li class="text -menu <%= "-active" if controller_name == 'about' %>"><%= link_to 'About', about_path %></li>
        </ul>
        <ul class="c-navigation -dark">
          <li class="text -menu js-btn-action" data-action="Share:toggle">Share</li>
          <% if controller_name == 'dashboards' || controller_name == 'countries' %>
            <li class="text -menu js-btn-action desktop" data-action="Data:toggle">Download</li>
            <li class="text -menu desktop">Print</li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/shared/_share_menu.html.erb
<div class="row">
  <div class="columns small-12">
    <div class="c-share-menu <%= class_name %>">
      <ul class="links text">
        <li class="js-btn-action" data-action="Share:toggle">
          <svg class="icon"><use xlink:href="#icon-share"></use></svg>
          <span>Share</span>
        </li>
        <% if controller_name == 'dashboards' || controller_name == 'countries' %>
          <li class="js-btn-action desktop" data-action="Data:toggle">
            <svg class="icon"><use xlink:href="#icon-download"></use></svg>
            <span>Download</span>
          </li>
          <li class="desktop">
            <a href="javascript:window.print()">
              <svg class="icon"><use xlink:href="#icon-print"></use></svg>
              <span>Print</span>
            </a>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/welcome/_impact-map.html.erb
<div class="spinner"></div>

<div id="homeMapView">

  <div class="row">
    <div class="columns small-12 medium-8">
      <h1 class="text -cta-title js-title">Stunting</h1>
      <h3 class="text -subtitle">Prevalence</h3>
    </div>
  </div>

  <div class="row">
    <div class="columns small-12 medium-8">
      <p class="text js-prevalence-text">Stunting affects 159 million children under five worldwide.</p>
    </div>
  </div>

  <div class="row">
    <div id="map-container" class="c-map-home"></div>

    <div class="columns small-12">
      <div id="mapLegendView" class="c-map-legend">
        <h4 class="text js-legend-title">Percentage of people affected</h4>
        <p class="text -footnote js-footnote">Source: <a href="http://www.globalnutritionreport.org/" target="_blank" rel="noopener">Global Nutrition Report 2016</a>, (drawing on: <a href="http://www.who.int/nutgrowthdb/estimates2014/en/" target="_blank" rel="noopener">UNICEF, WHO and World Bank 2015)</a>; India data based on <a href="http://wcd.nic.in/sites/default/files/State%20RSOC.pdf" target="_blank" rel="noopener">Rapid Survey of Children: 2013-4</a></p>
        <div class="buckets text -legend">
          <div class="bucket"><span class="bc1"></span></div>
          <div class="bucket"><span class="bc2"></span></div>
          <div class="bucket"><span class="bc3"></span></div>
          <div class="bucket"><span class="bc4"></span></div>
          <div class="bucket"><span class="bc5"></span></div>
          <div class="bucket"><span class="bc6"></span></div>
          <div class="bucket"><span class="bc7"></span></div>
          <div class="bucket"><span class="default">no data</span></div>
        </div>
      </div>
    </div>
  </div>

  <!-- <div class="columns small-12 medium-7">
    <h3 class="text -subtitle">Current funding and future resources needs</h3>
    <p class="text">How much has the world spent on <span class="js--funding-needs-target -bold"></span> since 2016, and how much further will it need to go in order to reach global targets by 2025?</p>
  </div>
  <div id="fundingProgressView" class="c-funding-progress"></div> -->
</div>

app/views/welcome/_impact-others.html.erb
<div class="row">
  <div class="columns small-12">
    <hr class="c-separator"/>
  </div>
  <div class="columns small-12 text centered">
    <p class="info text -cta-text">Other nutrition targets (not included in the analysis)</p>
  </div>
  <div class="columns small-12">
    <div class="c-goal-box">
      <div class="row">
        <div class="columns small-12 medium-6">
          <div class="title -first">
            <svg class="icon"><use xlink:href="#icon-weight"></use></svg>
            <h4 class="text -goal-title">Low birth weight</h4>
          </div>
        </div>
        <div class="columns small-12 medium-6">
          <div class="title">
            <svg class="icon"><use xlink:href="#icon-weight-up"></use></svg>
            <h4 class="text -goal-title">Overweight</h4>
          </div>
        </div>
        <p class="text">Assessment of the WHA nutrition targets on childhood overweight and low birthweight was not included because, at the time of this analysis, there were either insufficient data on the prevalence of the condition (low birthweight) or consensus on effective interventions to reach the goal (child overweight). See <a href="http://apps.who.int/iris/bitstream/10665/204176/1/9789241510066_eng.pdf" target="_blank" rel="noopener">here</a> for emerging recommendations on a package of interventions to address childhood overweight.</p>
      </div>
    </div>
  </div>
  <div class="columns small-12">
    <hr class="c-separator"/>
  </div>
</div>